config/routes.rb
Rails.application.routes.draw do
  get 'make_a_transaction/index'

  get 'invest_cash/deposit'

  get 'invest_cash/my_deposits'

  get 'invest_cash/withdraw'

  get 'invest_cash/earning_statement'

  get 'invest_cash/deposit_history'

  get 'invest_cash/withdraw_history'

  get 'withdraw_cash/withdraw_to_agent'

  get 'withdraw_cash/withdraw_to_bank'

  get 'withdraw_cash/withdraw_to_mobile'

  get 'transfer_money/within_money_transfer'

  get 'transfer_money/transfer_to_banks'

  get 'transfer_money/mobile_banks'

  get 'make_a_transaction/deposit_from_mpesa'

  get 'make_a_transaction/transfer_money'

  get 'make_a_transaction/buy_airtime'

  get 'make_a_transaction/bulk_payment'

  get 'make_a_transaction/withdraw_cash'

  get 'make_a_transaction/invest_your_money'

  root 'simple_pages#index'

  get 'simple_pages/make_a_transaction'

  get 'simple_pages/view_activity'

  get 'simple_pages/cash_advance'

  get 'simple_pages/reports'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invest_cash_controller.rb
class InvestCashController < ApplicationController
  def deposit
  end

  def my_deposits
  end

  def withdraw
  end

  def earning_statement
  end

  def deposit_history
  end

  def withdraw_history
  end
end

app/controllers/make_a_transaction_controller.rb
class MakeATransactionController < ApplicationController
  def deposit_from_mpesa
  end

  def transfer_money
  end

  def buy_airtime
  end

  def bulk_payment
  end

  def withdraw_cash
  end

  def invest_your_money
  end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def make_a_transaction
  end

  def view_activity
  end

  def cash_advance
  end

  def reports
  end
end

app/controllers/transfer_money_controller.rb
class TransferMoneyController < ApplicationController
  def within_money_transfer
  end

  def transfer_to_banks
  end

  def mobile_banks
  end
end

app/controllers/withdraw_cash_controller.rb
class WithdrawCashController < ApplicationController
  def withdraw_to_agent
  end

  def withdraw_to_bank
  end

  def withdraw_to_mobile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invest_cash_helper.rb
module InvestCashHelper
end

app/helpers/make_a_transaction_helper.rb
module MakeATransactionHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/transfer_money_helper.rb
module TransferMoneyHelper
end

app/helpers/withdraw_cash_helper.rb
module WithdrawCashHelper
end

app/views/invest_cash/deposit.html.erb
<h1>InvestCash#deposit</h1>
<p>Find me in app/views/invest_cash/deposit.html.erb</p>

app/views/invest_cash/deposit_history.html.erb
<h1>InvestCash#deposit_history</h1>
<p>Find me in app/views/invest_cash/deposit_history.html.erb</p>

app/views/invest_cash/earning_statement.html.erb
<h1>InvestCash#earning_statement</h1>
<p>Find me in app/views/invest_cash/earning_statement.html.erb</p>

app/views/invest_cash/my_deposits.html.erb
<h1>InvestCash#my_deposits</h1>
<p>Find me in app/views/invest_cash/my_deposits.html.erb</p>

app/views/invest_cash/withdraw.html.erb
<h1>InvestCash#withdraw</h1>
<p>Find me in app/views/invest_cash/withdraw.html.erb</p>

app/views/invest_cash/withdraw_history.html.erb
<h1>InvestCash#withdraw_history</h1>
<p>Find me in app/views/invest_cash/withdraw_history.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="TopHeader">
        <div class="TopHeader_Container">


            <span class="Welcome"> Welcome <a href="/users/37359/edit">CHRIS HATENS</a> </span>
            <ul class="TopLinks">
                <li class="menu">
                    <!--<li >-->
                    <ul class="sf-menu">

                        <li>
                            <a href="/account_settings">Menu</a>
                            <ul>
                                <li><a href="/account_settings">Account settings</a></li>
                                <li><a href="/companies/34967/account_configuration/edit">API settings</a></li>
                                <li><a href="/users/37359/edit">Profile</a></li>
                                <li><a href="/audits">Audit logs</a></li>
                                <li><a href="/direct_deposits">Direct deposits</a></li>
                                <li><a href="/financial_statements">Account statement</a></li>
                                <li><a href="/messages">SMS logs</a></li>
                                <li><a href="/sms_bundles">SMS bundles</a></li>
                                <!-- <li><a href="/referral">Referrals</a></li> -->

                                <!--<li></li>-->
                            </ul>
                        </li>
                    </ul>
                    <!--</li>-->

                    <b class="caret MenuArrow"></b> </li>
                <li><a href="/help">Help</a></li>
                |
                <li><a rel="nofollow" data-method="delete" href="/users/sign_out">Sign out</a></li>
            </ul>
        </div>
    </div>

    <!--End TopHeader-->

    <div id="HeaderContent_area">
        <img class="Logo" src="/assets/logo.png" alt="Logo">
        <!-- Navigation -->
        <ul class="MainMenu">
            <li><a class="LeftTab current" id="Dashboard_tab" href="/">Dashboard</a></li>
            <li><a class="NormalTab" data-step="4" data-intro="See your transaction details here, all in one place" data-position="right" id="Transactions_tab" href="/simple_pages/make_a_transaction">Make A Transaction</a></li>
            <li><a class="NormalTab" data-step="5" data-intro="Pay allows you to make bulk payments to external entities" data-position="right" id="Pay_tab" href="/simple_pages/view_activity">View Activity</a></li>
            <li><a class="NormalTab" data-step="2" data-intro="You can also transfer funds and view your past transfer details here." data-position="right" id="Transfers_tab" href="/simple_pages/cash_advance">Cash Advance</a></li>
            <li><a class="RightTab" id="CashAdvance_tab" href="/simple_pages/reports">Reports</a></li>
        </ul>


        <div id="HeaderSeparator"></div>

    </div>

<%= yield %>
<div class="FooterContainer">
        <div class="Footer">
            <a href="/privacy">Privacy policy</a> | <a href="/tos"> Terms of service</a> | <a href="/msa">Merchant service agreement</a> | <a href="/lnm">Lipa Na M-PESA terms and conditions</a> | <a href="/contact_us">Contact us</a>
            <br> © Copyright 2018 thaErrorAssets, Inc.
        </div>
</body>
</html>

app/views/make_a_transaction/bulk_payment.html.erb
<div class="content">



        <div class="SubHeader">
            <ul>
                <li><a class="current" href="/make_a_transaction/deposit_from_mpesa">Deposit from MPESA </a></li>
                <li><a href="/make_a_transaction/transfer_money">Transfer Money</a></li>
                <li><a class="current" href="/make_a_transaction/buy_airtime">Buy Airtime</a></li>
                <li><a href="/make_a_transaction/bulk_payment">Bulk Payment</a></li>
                <li><a class="current" href="/make_a_transaction/withdraw_cash">Withdraw Cash</a></li>
                <li><a class="current" href="/make_a_transaction/invest_your_money">Invest Your Money</a></li>
            </ul>
        </div><br>



        <div class="content">

app/views/make_a_transaction/buy_airtime.html.erb
<div class="content">



        <div class="SubHeader">
            <ul>
                <li><a class="current" href="/make_a_transaction/deposit_from_mpesa">Deposit from MPESA </a></li>
                <li><a href="/make_a_transaction/transfer_money">Transfer Money</a></li>
                <li><a class="current" href="/make_a_transaction/buy_airtime">Buy Airtime</a></li>
                <li><a href="/make_a_transaction/bulk_payment">Bulk Payment</a></li>
                <li><a class="current" href="/make_a_transaction/withdraw_cash">Withdraw Cash</a></li>
                <li><a class="current" href="/make_a_transaction/invest_your_money">Invest Your Money</a></li>
            </ul>
        </div><br>



        <div class="content">

app/views/make_a_transaction/deposit_from_mpesa.html.erb
<div class="content">



        <div class="SubHeader">
            <ul>
                <li><a class="current" href="/make_a_transaction/deposit_from_mpesa">Deposit from MPESA </a></li>
                <li><a href="/make_a_transaction/transfer_money">Transfer Money</a></li>
                <li><a class="current" href="/make_a_transaction/buy_airtime">Buy Airtime</a></li>
                <li><a href="/make_a_transaction/bulk_payment">Bulk Payment</a></li>
                <li><a class="current" href="/make_a_transaction/withdraw_cash">Withdraw Cash</a></li>
                <li><a class="current" href="/make_a_transaction/invest_your_money">Invest Your Money</a></li>
            </ul>
        </div><br>



        <div class="content">




        <!-- If there are no campaigns then add content to display. -->
        <div class="NoData_container PushDown_65">
            <h1 class="NoData_header"><span class="BlueText ">Direct </span>deposits</h1>
            <p class="NoData_mainText">You can deposit money into your HITSAVEGROUP account  Go to your Lipa Na Mpesa menu, select the Paybill option and use <span class="BlueText "> <b>678083</b> </span> as the business
                number, <span class="BlueText "> <b>ONLINEDEPOSIT</b> </span> as the account number, then enter the amount. Once payment is complete you can 'Claim' the deposit from this page. </p>
        </div>


        <div class="TopDate_container">
            <h1>Direct deposits</h1>
            <table class="table TopDate_filterContainer">

                <tbody>
                    <tr>
                        <td><label>Select date</label></td>
                        <td><input type="text" name="daterange" id="daterange" value="19/12/2018 - 26/12/2018" class="small rangepicker">
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <a href="#myModal" role="button" data-toggle="modal" class="MainButton_large MainButton_orange ">
  Settle direct deposit </a>

        <div class="PushDown_header"></div>


        <div class="modal" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">Claim direct deposit</h3>
            </div>

            <form action="direct_deposits/claim" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="270bYZewlz7cQRQXe9ovMAgTjs76mv6cE88R9bEbU5VxMSRxzyqJKxcXAv1Ei1ZHLuMx8geHzTpEls0ufqaHAw==">
                <div class="SmallRow clearfix">
                    <label class="RowForm_label">Enter phone number</label>
                    <input type="text" name="phone_number" id="phone_number" value="" autocomplete="off" class="SmallRow_textfield">
                </div>

                <div class="SmallRow clearfix">
                    <label class="RowForm_label">Enter Mpesa code</label>
                    <input type="text" name="mpesa_code" id="mpesa_code" value="" autocomplete="off" class="SmallRow_textfield">
                </div>

                <div class="SmallRow_footer clearfix">
                    <input type="submit" name="commit" value="Claim" data-disable-with="Please wait..." class="MainButton_large MainButton_blue">
                </div>
            </form>
        </div>

        <div id="direct_deposits_table_wrapper" class="dataTables_wrapper" role="grid">
            <div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-tl ui-corner-tr ui-helper-clearfix">
                <div id="direct_deposits_table_length" class="dataTables_length"><label>Show <select size="1" name="direct_deposits_table_length" aria-controls="direct_deposits_table"><option value="10" selected="selected">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div>
                <div
                    class="dataTables_filter" id="direct_deposits_table_filter"><label>Search: <input type="text" aria-controls="direct_deposits_table"></label></div>
            <div id="direct_deposits_table_processing" class="dataTables_processing" style="visibility: hidden;">Processing...</div>
            <div class="DTTT_container ui-buttonset ui-buttonset-multi" style="position: relative;"><button class="DTTT_button DTTT_button_collection ui-button ui-state-default" id="ToolTables_direct_deposits_table_0"><span>Export As</span></button></div>
            <div class="clear"></div>
        </div>
        <table id="direct_deposits_table" class="display display-mouse-pointer dataTable" aria-describedby="direct_deposits_table_info">
            <thead>
                <tr role="row">
                    <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="direct_deposits_table" rowspan="1" colspan="1" aria-sort="descending" aria-label="Date: activate to sort column ascending">
                        <div class="DataTables_sort_wrapper">Date<span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span></div>
                    </th>
                    <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="direct_deposits_table" rowspan="1" colspan="1" aria-label="Amount: activate to sort column ascending">
                        <div class="DataTables_sort_wrapper">Amount<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    </th>
                    <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="direct_deposits_table" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending">
                        <div class="DataTables_sort_wrapper">Phone<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    </th>
                    <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="direct_deposits_table" rowspan="1" colspan="1" aria-label="External Reference: activate to sort column ascending">
                        <div class="DataTables_sort_wrapper">External Reference<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    </th>
                    <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="direct_deposits_table" rowspan="1" colspan="1" aria-label="Type: activate to sort column ascending">
                        <div class="DataTables_sort_wrapper">Type<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    </th>
                    <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="direct_deposits_table" rowspan="1" colspan="1" aria-label="Status: activate to sort column ascending">
                        <div class="DataTables_sort_wrapper">Status<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    </th>
                </tr>
            </thead>

            <tbody class="tbodytab2" role="alert" aria-live="polite" aria-relevant="all">
                <tr class="odd">
                    <td valign="top" colspan="6" class="dataTables_empty">No data available in table</td>
                </tr>
            </tbody>
        </table>
        <div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix">
            <div class="dataTables_info" id="direct_deposits_table_info">Showing 0 to 0 of 0 entries</div>
            <div class="dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers" id="direct_deposits_table_paginate"><a tabindex="0" class="first ui-corner-tl ui-corner-bl fg-button ui-button ui-state-default ui-state-disabled" id="direct_deposits_table_first">First</a><a tabindex="0" class="previous fg-button ui-button ui-state-default ui-state-disabled"
                    id="direct_deposits_table_previous">Previous</a><span></span><a tabindex="0" class="next fg-button ui-button ui-state-default ui-state-disabled" id="direct_deposits_table_next">Next</a><a tabindex="0" class="last ui-corner-tr ui-corner-br fg-button ui-button ui-state-default ui-state-disabled"
                    id="direct_deposits_table_last">Last</a></div>
        </div>
    </div>
    </div>
    <!-- end .content-box -->

    <div class="PushTop_65"></div>

app/views/make_a_transaction/invest_your_money.html.erb
<div class="content">



        <div class="SubHeader">
            <ul>
                <li><a class="current" href="/make_a_transaction/deposit_from_mpesa">Deposit from MPESA </a></li>
                <li><a href="/make_a_transaction/transfer_money">Transfer Money</a></li>
                <li><a class="current" href="/make_a_transaction/buy_airtime">Buy Airtime</a></li>
                <li><a href="/make_a_transaction/bulk_payment">Bulk Payment</a></li>
                <li><a class="current" href="/make_a_transaction/withdraw_cash">Withdraw Cash</a></li>
                <li><a class="current" href="/make_a_transaction/invest_your_money">Invest Your Money</a></li>
            </ul>
        </div><br>



        <div class="content">

app/views/make_a_transaction/transfer_money.html.erb
<div class="content">



        <div class="SubHeader">
            <ul>
                <li><a class="current" href="/make_a_transaction/deposit_from_mpesa">Deposit from MPESA </a></li>
                <li><a href="/make_a_transaction/transfer_money">Transfer Money</a></li>
                <li><a class="current" href="/make_a_transaction/buy_airtime">Buy Airtime</a></li>
                <li><a href="/make_a_transaction/bulk_payment">Bulk Payment</a></li>
                <li><a class="current" href="/make_a_transaction/withdraw_cash">Withdraw Cash</a></li>
                <li><a class="current" href="/make_a_transaction/invest_your_money">Invest Your Money</a></li>
            </ul>
        </div><br>



        <div class="content">

app/views/make_a_transaction/withdraw_cash.html.erb
<div class="content">



        <div class="SubHeader">
            <ul>
                <li><a class="current" href="/make_a_transaction/deposit_from_mpesa">Deposit from MPESA </a></li>
                <li><a href="/make_a_transaction/transfer_money">Transfer Money</a></li>
                <li><a class="current" href="/make_a_transaction/buy_airtime">Buy Airtime</a></li>
                <li><a href="/make_a_transaction/bulk_payment">Bulk Payment</a></li>
                <li><a class="current" href="/make_a_transaction/withdraw_cash">Withdraw Cash</a></li>
                <li><a class="current" href="/make_a_transaction/invest_your_money">Invest Your Money</a></li>
            </ul>
        </div><br>



        <div class="content">

app/views/simple_pages/cash_advance.html.erb
<h1>SimplePages#cash_advance</h1>
<p>Find me in app/views/simple_pages/cash_advance.html.erb</p>

app/views/simple_pages/index.html.erb
<div class="content">

        <div class="card-summary-container PushTop_25 clearfix">
            <div class="card-summary-box card-summary-two-col FloatLeft clearfix">

                <div class="card-summary-header card-summary-header-figures-container clearfix">
                    <div class="PushLeft_10">
                        <span class="card-summary-figures">Ksh 0.13</span>
                        <small>Current balance</small>
                    </div>
                </div>

                <div class="card-summary-header-figures-container clearfix">
                    <div class="PushLeft_10">
                        <span class="card-summary-figures">Ksh 0.13</span>
                        <small>Available balance</small>
                    </div>
                </div>
            </div>

            <div class="card-summary-box card-summary-one-col PushLeft_30 FloatLeft clearfix">
                <h4>Invest your money</h4>
                <div class="card-summary-body clearfix">
                    <p>Make an investment of your money and enjoy Profits</p>
                    <div class="card-summary-one-col-button">
                        <a class="MainButton MainButton_orange card-summary-one-col-inputbutton" href="/transfers/transfer">Invest Now</a>
                    </div>
                </div>
            </div>

            <div class="card-summary-box card-summary-one-col FloatRight clearfix">
                <h4 class="PushLeft_5">Withdraw</h4>
                <div class="card-summary-body clearfix">
                    <p>Get your funds back to your hand in no min.</p>
                    <div class="card-summary-one-col-button">
                        <a class="MainButton MainButton_blue card-summary-one-col-button" href="/pay/payments/new"><span class="translation_missing" title="translation missing: en.pay.payments.pay_now">Withdraw Now</span></a>
                    </div>
                </div>
            </div>
        </div>




            

        <div class="PushTop_45  clearfix">
            <ul class="nav nav-tabs NewNav_container">
                <li><a href="/pay_merchant_recipients">Last Investment</a></li>
                <li class="active"><a href="#">Last Investment Withdrawal</a></li>
            </ul>

            <div id="external_mpesa_wallets_table_wrapper" class="dataTables_wrapper" role="grid">
                <div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-tl ui-corner-tr ui-helper-clearfix">
                    <div id="external_mpesa_wallets_table_length" class="dataTables_length"><label>Show <select size="1" name="external_mpesa_wallets_table_length" aria-controls="external_mpesa_wallets_table"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100" selected="selected">100</option></select> entries</label></div>
                    <div
                        class="dataTables_filter" id="external_mpesa_wallets_table_filter"><label>Search: <input type="text" aria-controls="external_mpesa_wallets_table"></label></div>
                <div id="external_mpesa_wallets_table_processing" class="dataTables_processing" style="visibility: hidden;">Processing...</div>
            </div>
            <table id="external_mpesa_wallets_table" class="display display-mouse-pointer dataTable" aria-describedby="external_mpesa_wallets_table_info">
                <thead>
                    <tr role="row">
                        <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="external_mpesa_wallets_table" rowspan="1" colspan="1" aria-sort="descending" aria-label="Name: activate to sort column ascending">
                            <div class="DataTables_sort_wrapper">Name<span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span></div>
                        </th>
                        <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="external_mpesa_wallets_table" rowspan="1" colspan="1" aria-label="Phone number: activate to sort column ascending">
                            <div class="DataTables_sort_wrapper">Phone number<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                        </th>
                        <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="external_mpesa_wallets_table" rowspan="1" colspan="1" aria-label="Created by: activate to sort column ascending">
                            <div class="DataTables_sort_wrapper">Created by<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                        </th>
                        <th class="ui-state-default" role="columnheader" tabindex="0" aria-controls="external_mpesa_wallets_table" rowspan="1" colspan="1" aria-label="Status: activate to sort column ascending">
                            <div class="DataTables_sort_wrapper">Status<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                        </th>
                    </tr>
                </thead>

                <tbody class="tbodytab2" role="alert" aria-live="polite" aria-relevant="all">
                    <tr class="odd" id="30392">
                        <td class=" sorting_1">ROBERT NDEGE ONDIEKI</td>
                        <td class="">+254715133551</td>
                        <td class="">CHRIS HATENS</td>
                        <td class="">Approved</td>
                    </tr>
                    <tr class="even" id="30973">
                        <td class=" sorting_1">NICHOLAS OMBASA OMWOYO</td>
                        <td class="">+254722455011</td>
                        <td class="">CHRIS HATENS</td>
                        <td class="">Approved</td>
                    </tr>
                    <tr class="odd" id="30515">
                        <td class=" sorting_1">MATHEW MAGEKA</td>
                        <td class="">+254711543474</td>
                        <td class="">CHRIS HATENS</td>
                        <td class="">Approved</td>
                    </tr>
                    <tr class="even" id="30974">
                        <td class=" sorting_1">AZENATH AKEYO OKUMU</td>
                        <td class="">+254725756834</td>
                        <td class="">CHRIS HATENS</td>
                        <td class="">Approved</td>
                    </tr>
                </tbody>
            </table>
            <div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix">
                <div class="dataTables_info" id="external_mpesa_wallets_table_info">Showing 1 to 4 of 4 entries</div>
                <div class="dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers" id="external_mpesa_wallets_table_paginate"><a tabindex="0" class="first ui-corner-tl ui-corner-bl fg-button ui-button ui-state-default ui-state-disabled" id="external_mpesa_wallets_table_first">First</a><a tabindex="0" class="previous fg-button ui-button ui-state-default ui-state-disabled"
                        id="external_mpesa_wallets_table_previous">Previous</a><span><a tabindex="0" class="fg-button ui-button ui-state-default ui-state-disabled">1</a></span><a tabindex="0" class="next fg-button ui-button ui-state-default ui-state-disabled"
                        id="external_mpesa_wallets_table_next">Next</a><a tabindex="0" class="last ui-corner-tr ui-corner-br fg-button ui-button ui-state-default ui-state-disabled" id="external_mpesa_wallets_table_last">Last</a></div>
            </div>
        </div>
        <div id="Pagination"></div>
    </div>
        

        




        <div class="push"></div>
    </div>

    <!-- end content -->

app/views/simple_pages/make_a_transaction.html.erb
  <ul>
    <li><%= link_to "Deposit from MPESA ", make_a_transaction_deposit_from_mpesa_path %></li>
    <li><%= link_to "Transfer Money", make_a_transaction_transfer_money_path %></li>
    <li><%= link_to "Buy Airtime", make_a_transaction_buy_airtime_path %></li>
    <li><%= link_to "Bulk Payment", make_a_transaction_bulk_payment_path %></li>
    <li><%= link_to "Withdraw Cash", make_a_transaction_withdraw_cash_path %></li>
    <li><%= link_to "Invest Your Money", make_a_transaction_invest_your_money_path %></li>
  </ul>
  <h1>COMPLETED TRANSACTIONS</h1>
<table id="customers">
  <tr>
    <th>TRANSACTION TYPE</th>
    <th>TIME & DATE</th>
    <th>TRANSACTION ID</th>
    <th>AMOUNT</th>
    <th>STATUS</th>
  </tr>
  <tr>
    <td>DEPOSIT FROM MPESA</td>
    <td>25.5.2018 23.00</td>
    <td>H25444152LK</td>
    <td>kes 50,000</td>
    <td>COMPLETED</td>
  </tr>
  
</table>

<li><%= link_to "REQUEST STATEMENT", simple_pages_cash_advance_path %></li>
<li><%= link_to "DOWNLOAD MINI - STATEMENT", simple_pages_cash_advance_path %></li>

app/views/simple_pages/reports.html.erb
<h1>SimplePages#reports</h1>
<p>Find me in app/views/simple_pages/reports.html.erb</p>

app/views/simple_pages/view_activity.html.erb
<h1>All Your Activity is Logged Here</h1>